<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Compass.SharedKernel\Compass.SharedKernel.csproj" />
    <ProjectReference Include="..\Planning.Contracts\Compass.Modules.Planning.Contracts.csproj" />
    <ProjectReference Include="..\..\Execution\Execution.Contracts\Compass.Modules.Execution.Contracts.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>
</Project>
