<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Planning\Planning\Compass.Modules.Planning.csproj" />
    <ProjectReference Include="..\..\Modules\Calendar\Calendar\Compass.Modules.Calendar.csproj" />
    <ProjectReference Include="..\..\Modules\Execution\Execution\Compass.Modules.Execution.csproj" />
    <ProjectReference Include="..\..\Modules\Planning\Planning.Infrastructure\Compass.Modules.Planning.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Execution\Execution.Infrastructure\Compass.Modules.Execution.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Calendar\Calendar.Infrastructure\Compass.Modules.Calendar.Infrastructure.csproj" />
  </ItemGroup>

</Project>

