// <auto-generated />
using System;
using Compass.Modules.Calendar.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Compass.Modules.Calendar.Infrastructure.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    partial class CalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("calendar")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Compass.Modules.Calendar.Infrastructure.Database.Models.ScheduleProfileData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ScheduleProfiles", "calendar");
                });

            modelBuilder.Entity("Compass.Modules.Calendar.Infrastructure.Database.Models.ScheduleWindowData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ScheduleProfileId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleProfileId");

                    b.ToTable("ScheduleWindows", "calendar");
                });

            modelBuilder.Entity("Compass.Modules.Calendar.Infrastructure.Database.Models.ScheduleWindowData", b =>
                {
                    b.HasOne("Compass.Modules.Calendar.Infrastructure.Database.Models.ScheduleProfileData", "Profile")
                        .WithMany("Windows")
                        .HasForeignKey("ScheduleProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Compass.Modules.Calendar.Infrastructure.Database.Models.ScheduleProfileData", b =>
                {
                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
