// <auto-generated />
using System;
using System.Collections.Generic;
using Compass.Modules.Execution.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Compass.Modules.Execution.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ExecutionDbContext))]
    [Migration("20260818013110_Initial_DailyPlan_Schema")]
    partial class Initial_DailyPlan_Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("execution")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DailyCycles.DailyCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("daily_cycles", "execution");
                });

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DailyCycles.ExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DailyCycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Interval", "Compass.Modules.Execution.Domain.DailyCycles.ExecutionLog.Interval#TimeInterval", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndTime");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartTime");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DailyCycleId");

                    b.ToTable("execution_logs", "execution");
                });

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DecisionEngine.DailyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Date")
                        .IsUnique();

                    b.ToTable("DailyPlans", "execution");
                });

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DecisionEngine.SuggestedExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DailyPlanId");

                    b.ToTable("DailyPlanItems", "execution");
                });

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DailyCycles.ExecutionLog", b =>
                {
                    b.HasOne("Compass.Modules.Execution.Domain.DailyCycles.DailyCycle", null)
                        .WithMany("Logs")
                        .HasForeignKey("DailyCycleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DecisionEngine.SuggestedExecution", b =>
                {
                    b.HasOne("Compass.Modules.Execution.Domain.DecisionEngine.DailyPlan", null)
                        .WithMany("Suggestions")
                        .HasForeignKey("DailyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DailyCycles.DailyCycle", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Compass.Modules.Execution.Domain.DecisionEngine.DailyPlan", b =>
                {
                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
