// <auto-generated />
using System;
using Compass.Domain.Enums;
using Compass.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Compass.Infrastructure.Migrations
{
    [DbContext(typeof(CompassDbContext))]
    [Migration("20260716155741_InitialProductionSchema")]
    partial class InitialProductionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "commitment_status", new[] { "archived", "blocked", "completed", "in_progress", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "commitment_type", new[] { "event", "habit", "note", "task" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "goal_status", new[] { "active", "cancelled", "completed", "on_hold" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Compass.Domain.Entities.Commitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("best_streak");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid?>("ConvertedToCommitmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_to_commitment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cron_expression");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<short>("EnergyRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("energy_required");

                    b.Property<int>("EstimatedDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("LocationOrLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_or_link");

                    b.Property<int>("PostponedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("postponed_count");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<CommitmentStatus>("Status")
                        .HasColumnType("commitment_status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<CommitmentType>("Type")
                        .HasColumnType("commitment_type")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConvertedToCommitmentId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_commitments_project_id")
                        .HasFilter("project_id IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_commitments_events_lookup")
                        .HasFilter("type = 'event' AND status != 'archived'");

                    b.HasIndex("UserId", "Status", "Type")
                        .HasDatabaseName("idx_commitments_now_engine")
                        .HasFilter("status IN ('pending', 'in_progress') AND type IN ('task', 'habit')");

                    b.ToTable("commitments", null, t =>
                        {
                            t.HasCheckConstraint("chk_commitment_title_length", "char_length(title) >= 3");

                            t.HasCheckConstraint("chk_event_time_validity", "(type != 'event') OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)");
                        });

                    b.HasDiscriminator<CommitmentType>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Dependency", b =>
                {
                    b.Property<Guid>("ParentCommitmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_commitment_id");

                    b.Property<Guid>("ChildCommitmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_commitment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ParentCommitmentId", "ChildCommitmentId");

                    b.HasIndex("ChildCommitmentId")
                        .HasDatabaseName("idx_dependencies_child_lookup");

                    b.ToTable("dependencies", null, t =>
                        {
                            t.HasCheckConstraint("chk_no_self_dependency", "parent_commitment_id != child_commitment_id");
                        });
                });

            modelBuilder.Entity("Compass.Domain.Entities.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ActualDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration_minutes");

                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("commitment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CommitmentId");

                    b.HasIndex("UserId", "StartTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_focus_sessions_user_history");

                    b.ToTable("focus_sessions", null, t =>
                        {
                            t.HasCheckConstraint("chk_focus_duration", "actual_duration_minutes > 0");

                            t.HasCheckConstraint("chk_focus_time_validity", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("Compass.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("progress_percentage");

                    b.Property<GoalStatus>("Status")
                        .HasColumnType("goal_status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WhyDescription")
                        .HasColumnType("text")
                        .HasColumnName("why_description");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("goals", null, t =>
                        {
                            t.HasCheckConstraint("chk_goal_progress", "progress_percentage BETWEEN 0.00 AND 100.00");

                            t.HasCheckConstraint("chk_goal_title_length", "char_length(title) >= 3");
                        });
                });

            modelBuilder.Entity("Compass.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<CommitmentStatus>("Status")
                        .HasColumnType("commitment_status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("TotalEstimatedDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_estimated_duration_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_projects_user_status");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("chk_project_duration", "total_estimated_duration_minutes >= 0");

                            t.HasCheckConstraint("chk_project_title_length", "char_length(title) >= 3");
                        });
                });

            modelBuilder.Entity("Compass.Domain.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CommitmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("commitment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sent");

                    b.Property<DateTime>("TriggerTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trigger_time");

                    b.HasKey("Id");

                    b.HasIndex("CommitmentId");

                    b.HasIndex("TriggerTime")
                        .HasDatabaseName("idx_reminders_unsent_trigger")
                        .HasFilter("is_sent = FALSE");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Compass.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("work_end");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("work_start");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("schedules", null, t =>
                        {
                            t.HasCheckConstraint("chk_schedule_day", "day_of_week BETWEEN 0 AND 6");

                            t.HasCheckConstraint("chk_schedule_time_order", "work_end > work_start");
                        });
                });

            modelBuilder.Entity("Compass.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("AutoPostponeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_postpone_enabled");

                    b.Property<TimeOnly>("DailyReviewTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasColumnName("daily_review_time")
                        .HasDefaultValueSql("'20:00:00'");

                    b.Property<short>("DefaultEnergyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("default_energy_level");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("dark")
                        .HasColumnName("theme");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId");

                    b.ToTable("settings", null, t =>
                        {
                            t.HasCheckConstraint("chk_default_energy_level", "default_energy_level BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Compass.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#6366F1")
                        .HasColumnName("color_hex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("chk_tag_color_hex", "color_hex ~* '^#[a-f0-9]{6}$'");

                            t.HasCheckConstraint("chk_tag_name_length", "char_length(name) >= 2");
                        });
                });

            modelBuilder.Entity("Compass.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("America/Sao_Paulo")
                        .HasColumnName("time_zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Compass.Domain.Entities.EventCommitment", b =>
                {
                    b.HasBaseType("Compass.Domain.Entities.Commitment");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("chk_commitment_title_length", "char_length(title) >= 3");

                            t.HasCheckConstraint("chk_event_time_validity", "(type != 'event') OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)");
                        });

                    b.HasDiscriminator().HasValue(CommitmentType.Event);
                });

            modelBuilder.Entity("Compass.Domain.Entities.HabitCommitment", b =>
                {
                    b.HasBaseType("Compass.Domain.Entities.Commitment");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("chk_commitment_title_length", "char_length(title) >= 3");

                            t.HasCheckConstraint("chk_event_time_validity", "(type != 'event') OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)");
                        });

                    b.HasDiscriminator().HasValue(CommitmentType.Habit);
                });

            modelBuilder.Entity("Compass.Domain.Entities.NoteCommitment", b =>
                {
                    b.HasBaseType("Compass.Domain.Entities.Commitment");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("chk_commitment_title_length", "char_length(title) >= 3");

                            t.HasCheckConstraint("chk_event_time_validity", "(type != 'event') OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)");
                        });

                    b.HasDiscriminator().HasValue(CommitmentType.Note);
                });

            modelBuilder.Entity("Compass.Domain.Entities.TaskCommitment", b =>
                {
                    b.HasBaseType("Compass.Domain.Entities.Commitment");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("chk_commitment_title_length", "char_length(title) >= 3");

                            t.HasCheckConstraint("chk_event_time_validity", "(type != 'event') OR (start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)");
                        });

                    b.HasDiscriminator().HasValue(CommitmentType.Task);
                });

            modelBuilder.Entity("Compass.Domain.Entities.Commitment", b =>
                {
                    b.HasOne("Compass.Domain.Entities.Commitment", null)
                        .WithMany()
                        .HasForeignKey("ConvertedToCommitmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Compass.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Compass.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Dependency", b =>
                {
                    b.HasOne("Compass.Domain.Entities.Commitment", null)
                        .WithMany()
                        .HasForeignKey("ChildCommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Domain.Entities.Commitment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.FocusSession", b =>
                {
                    b.HasOne("Compass.Domain.Entities.Commitment", null)
                        .WithMany()
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Goal", b =>
                {
                    b.HasOne("Compass.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Project", b =>
                {
                    b.HasOne("Compass.Domain.Entities.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Compass.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("Compass.Domain.Entities.Commitment", null)
                        .WithMany()
                        .HasForeignKey("CommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Compass.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Setting", b =>
                {
                    b.HasOne("Compass.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Compass.Domain.Entities.Setting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Compass.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Compass.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
